### ISSUE TITLE
Crash while holding down right click

### ISSUE THREAD

**Issue by superaxander** [amadornes/SCM-Localization-Issues#112]
I was holding down right click on a circuit while I scrolled through my hotbar after I had just rotated the circuit. For some reason, it tried to cast a wire to a plate. The crash starts at line 4482. This is on the FTB unstable(version 4.2.8) modpack with just SCM added.

[Crashlog](http://paste.feed-the-beast.com/view/27845212)
Excerpt:

```
[17:38:27] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@2fea7986:
java.lang.ClassCastException: com.amadornes.rscircuits.component.wire.ComponentWire cannot be cast to com.amadornes.rscircuits.component.misc.ComponentPlate
        at com.amadornes.rscircuits.component.misc.ComponentPlate$Factory.getPlacementData(ComponentPlate.java:135) ~[ComponentPlate$Factory.class:?]
        at com.amadornes.rscircuits.client.ClientProxy.handleDrawTick(ClientProxy.java:804) ~[ClientProxy.class:?]
        at com.amadornes.rscircuits.client.ClientProxy.drawInteractionPrevention(ClientProxy.java:710) ~[ClientProxy.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_511_ClientProxy_drawInteractionPrevention_RightClickBlock.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1001) [ForgeHooks.class:?]
        at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:387) [blm.class:?]
        at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518) [bcx.class:?]
        at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2195) [bcx.class:?]
        at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961) [bcx.class:?]
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749) [bcx.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) [bcx.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by amadornes** [comment]
Already fixed :)
