### ISSUE TITLE
Charset and scm 

### ISSUE THREAD

**Issue by sebdomsan54** [amadornes/SCM-Localization-Issues#175]
if you use Charset wire out of a circuit the game crashes but only when the circuit has bundled wire as the output 

> 
-- Head --
Thread: Server thread
Stacktrace:
	at com.amadornes.rscircuits.component.wire.ComponentWireBundled.getOutputSignal(ComponentWireBundled.java:138)
	at com.amadornes.rscircuits.circuit.Circuit.lambda$getOutput$28(Circuit.java:886)
	at com.amadornes.rscircuits.circuit.Circuit$$Lambda$719/1860106156.accept(Unknown Source)
	at com.amadornes.rscircuits.circuit.Circuit.forEachEdge(Circuit.java:580)
	at com.amadornes.rscircuits.circuit.Circuit.getOutput(Circuit.java:879)
	at com.amadornes.rscircuits.part.PartCircuit.getWeakSignal(PartCircuit.java:855)
	at pl.asie.charset.wires.WireUtils.getRedstoneLevel(WireUtils.java:125)
	at pl.asie.charset.wires.logic.PartWireNormal.propagate(PartWireNormal.java:188)
	at pl.asie.charset.wires.logic.PartWireInsulated.onSignalChanged(PartWireInsulated.java:34)
	at pl.asie.charset.wires.logic.PartWireSignalBase.logicUpdate(PartWireSignalBase.java:76)
	at pl.asie.charset.lib.wires.PartWire.func_73660_a(PartWire.java:441)
	at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:328)

-- Block entity being ticked --
Details:
	Name: mcmultipart:multipart.ticking // mcmultipart.block.TileMultipartContainer.Ticking
	Block type: ID #497 (tile.null // mcmultipart.block.BlockMultipartContainer)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1,4,17), Chunk: (at 1,0,1 in 0,1; contains blocks 0,0,16 to 15,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #497 (tile.null // mcmultipart.block.BlockMultipartContainer)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

**Comment by amadornes** [comment]
What version of SCM are you using? Because this should've been fixed in 1.0.3 :/
