### ISSUE TITLE
Crash when placing circuit with saved contents

### ISSUE THREAD

**Issue by heldplayer** [amadornes/SCM-Localization-Issues#19]
Circuit was obtained by breaking in survival mode.

Stack trace:
```
java.lang.NullPointerException: Ticking block entity
	at com.amadornes.rscircuits.part.PartCircuit$Circuit.notifyUpdate(PartCircuit.java:1033)
	at com.amadornes.rscircuits.part.PartCircuit$Circuit.notifyUpdate(PartCircuit.java:1010)
	at com.amadornes.rscircuits.component.ComponentWire.lambda$notifyNonWires$12(ComponentWire.java:451)
	at com.amadornes.rscircuits.component.ComponentWire$$Lambda$103/1955096882.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.amadornes.rscircuits.component.ComponentWire.notifyNonWires(ComponentWire.java:449)
	at com.amadornes.rscircuits.component.ComponentWireBundled.lambda$propagate$4(ComponentWireBundled.java:349)
	at com.amadornes.rscircuits.component.ComponentWireBundled$$Lambda$93/1912345185.accept(Unknown Source)
	at java.util.Map.forEach(Map.java:630)
	at com.amadornes.rscircuits.component.ComponentWireBundled.propagate(ComponentWireBundled.java:348)
	at com.amadornes.rscircuits.component.ComponentWireBundled.onCircuitAdded(ComponentWireBundled.java:191)
	at com.amadornes.rscircuits.part.PartCircuit$$Lambda$89/27871371.accept(Unknown Source)
	at com.amadornes.rscircuits.part.PartCircuit$Circuit.forEach(PartCircuit.java:1139)
	at com.amadornes.rscircuits.part.PartCircuit$Circuit.access$000(PartCircuit.java:865)
	at com.amadornes.rscircuits.part.PartCircuit.func_73660_a(PartCircuit.java:364)
	at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:324)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

Full crash report can be found [https://ss.heldplayer.blue/C8ELjweE](here)

**Comment by amadornes** [comment]
Going to close this because it's pretty much the same thing as #26 and the title is more generic
