### ISSUE TITLE
Crash when breaking bundled wire near RFTools timer

### ISSUE THREAD

**Issue by KaosSpectrum** [amadornes/SCM-Localization-Issues#275]
Here is the crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.96-ex110.jar)
  LoadingPlugin (Quark-r1.0-59.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.294.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.3.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 03/12/16 19:13
Description: Exception while updating neighbours

java.lang.NullPointerException: Exception while updating neighbours
        at com.amadornes.rscircuits.component.wire.ComponentWireBundled.getOutputSignal(ComponentWireBundled.java:138)
        at com.amadornes.rscircuits.circuit.Circuit.lambda$getOutput$28(Circuit.java:886)
        at com.amadornes.rscircuits.circuit.Circuit.forEachEdge(Circuit.java:580)
        at com.amadornes.rscircuits.circuit.Circuit.getOutput(Circuit.java:879)
        at com.amadornes.rscircuits.part.PartCircuit.getWeakSignal(PartCircuit.java:855)
        at mcmultipart.multipart.MultipartRedstoneHelper.getWeakSignal(MultipartRedstoneHelper.java:66)
        at mcmultipart.multipart.MultipartRedstoneHelper.getWeakSignal(MultipartRedstoneHelper.java:22)
        at mcmultipart.multipart.MultipartContainer.getWeakSignal(MultipartContainer.java:392)
        at mcmultipart.block.BlockMultipartContainer.func_180656_a(BlockMultipartContainer.java:318)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185911_a(BlockStateContainer.java:375)
        at net.minecraft.world.World.func_175651_c(World.java:3244)
        at mcjty.rftools.blocks.logic.generic.LogicSlabBlock.getInputStrength(LogicSlabBlock.java:113)
        at mcjty.rftools.blocks.logic.generic.LogicSlabBlock.checkRedstone(LogicSlabBlock.java:134)
        at mcjty.lib.container.GenericBlock.func_189540_a(GenericBlock.java:166)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:463)
        at net.minecraft.world.World.func_180496_d(World.java:519)
        at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.notifyConduitNeighbours(RedstoneConduitNetwork.java:179)
        at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.updateInputsFromConduit(RedstoneConduitNetwork.java:68)
        at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.addConduit(RedstoneConduitNetwork.java:60)
        at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.addConduit(RedstoneConduitNetwork.java:24)
        at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:50)
        at crazypants.enderio.conduit.AbstractConduitNetwork.init(AbstractConduitNetwork.java:37)
        at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.init(RedstoneConduitNetwork.java:38)
        at crazypants.enderio.conduit.ConduitUtil.ensureValidNetwork(ConduitUtil.java:57)
        at crazypants.enderio.conduit.AbstractConduit.updateNetwork(AbstractConduit.java:456)
        at crazypants.enderio.conduit.AbstractConduit.updateEntity(AbstractConduit.java:403)
        at crazypants.enderio.conduit.redstone.InsulatedRedstoneConduit.updateEntity(InsulatedRedstoneConduit.java:196)
        at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:235)
        at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)
        at net.minecraft.world.World.func_72939_s(World.java:1804)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at com.amadornes.rscircuits.component.wire.ComponentWireBundled.getOutputSignal(ComponentWireBundled.java:138)
        at com.amadornes.rscircuits.circuit.Circuit.lambda$getOutput$28(Circuit.java:886)
        at com.amadornes.rscircuits.circuit.Circuit.forEachEdge(Circuit.java:580)
        at com.amadornes.rscircuits.circuit.Circuit.getOutput(Circuit.java:879)
        at com.amadornes.rscircuits.part.PartCircuit.getWeakSignal(PartCircuit.java:855)
        at mcmultipart.multipart.MultipartRedstoneHelper.getWeakSignal(MultipartRedstoneHelper.java:66)
        at mcmultipart.multipart.MultipartRedstoneHelper.getWeakSignal(MultipartRedstoneHelper.java:22)
        at mcmultipart.multipart.MultipartContainer.getWeakSignal(MultipartContainer.java:392)
        at mcmultipart.block.BlockMultipartContainer.func_180656_a(BlockMultipartContainer.java:318)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185911_a(BlockStateContainer.java:375)
        at net.minecraft.world.World.func_175651_c(World.java:3244)
        at mcjty.rftools.blocks.logic.generic.LogicSlabBlock.getInputStrength(LogicSlabBlock.java:113)
        at mcjty.rftools.blocks.logic.generic.LogicSlabBlock.checkRedstone(LogicSlabBlock.java:134)
        at mcjty.lib.container.GenericBlock.func_189540_a(GenericBlock.java:166)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:463)

-- Block being updated --
Details:
        Source block type: ID #1438 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
        Block: rftools:timer_block[intermediate=0,logic_facing=down_tonorth,output=false]
        Block location: World: (-8,65,-8), Chunk: (at 8,4,8 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
        at net.minecraft.world.World.func_180496_d(World.java:519)
        at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.notifyConduitNeighbours(RedstoneConduitNetwork.java:179)
        at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.updateInputsFromConduit(RedstoneConduitNetwork.java:68)
        at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.addConduit(RedstoneConduitNetwork.java:60)
        at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.addConduit(RedstoneConduitNetwork.java:24)
        at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:50)
        at crazypants.enderio.conduit.AbstractConduitNetwork.init(AbstractConduitNetwork.java:37)
        at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.init(RedstoneConduitNetwork.java:38)
        at crazypants.enderio.conduit.ConduitUtil.ensureValidNetwork(ConduitUtil.java:57)
        at crazypants.enderio.conduit.AbstractConduit.updateNetwork(AbstractConduit.java:456)
        at crazypants.enderio.conduit.AbstractConduit.updateEntity(AbstractConduit.java:403)
        at crazypants.enderio.conduit.redstone.InsulatedRedstoneConduit.updateEntity(InsulatedRedstoneConduit.java:196)
        at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:235)
        at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)

-- Block entity being ticked --
Details:
        Name: blockConduitBundleTileEntity // crazypants.enderio.conduit.TileConduitBundle
        Block type: ID #1438 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-8,65,-7), Chunk: (at 8,4,9 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
        Actual block type: ID #1438 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1804)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
        Level name: world
        All players: 1 total; [EntityPlayerMP['TheDigitalMiner'/458, l='world', x=-7.53, y=65.13, z=-8.96]]
        Chunk stats: ServerChunkCache: 441 Drop: 0
        Level seed: 6903202304614250429
        Level generator: ID 00 - default, ver 1. Features enabled: false
        Level generator options:
        Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Level time: 0 game time, 0 day time
        Level dimension: 0
        Level storage version: 0x00000 - Unknown?
        Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
        Minecraft Version: 1.10.2
        Operating System: Linux (amd64) version 2.6.32-642.3.1.el6.x86_64
        Java Version: 1.8.0_101, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 287351960 bytes (274 MB) / 1273659392 bytes (1214 MB) up to 2075918336 bytes (1979 MB)
        JVM Flags: 9 total; -Xms512M -Xmx2048M -XX:PermSize=256M -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
        IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
        FML: MCP 9.32 Powered by Forge 12.18.2.2124 97 mods loaded, 97 mods active

**Comment by KaosSpectrum** [comment]
Is there a way to get my server booted again?

**Comment by convict999** [comment]
you have the coords in the log, try replacing it before it ticks. or mcEdit
