### ISSUE TITLE
Crash when using holding tiny Redstone

### ISSUE THREAD

**Issue by Speiger** [amadornes/SCM-Localization-Issues#281]
Well i am playing with a couple people on a testserver and i wanted to make full use of the IC2C/SCM compat allowing me to make a Toggle letch on 1 block and as soon as i holded tiny redstone dust in my hand i got a client crash.

```
java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=ticking, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in ExtendedBlockState{block=mcmultipart:multipart, properties=[ticking]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at mcmultipart.block.BlockMultipartContainer.func_176201_c(BlockMultipartContainer.java:484)
	at net.minecraft.block.state.BlockStateBase.getMetadata(BlockStateBase.java:63)
	at RenderEnv.getMetadata(RenderEnv.java:133)
	at CustomColors.getColorMultiplier(CustomColors.java:888)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsFlat(BlockModelRenderer.java:393)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:154)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:86)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
	at com.amadornes.rscircuits.component.SimpleFactory.draw(SimpleFactory.java:166)
	at com.amadornes.rscircuits.component.wire.ComponentWire$Factory.drawPlacement(ComponentWire.java:617)
	at com.amadornes.rscircuits.component.wire.ComponentWire$Factory.drawPlacement(ComponentWire.java:533)
	at com.amadornes.rscircuits.part.PartCircuit.drawComponentHighlight(PartCircuit.java:721)
	at com.amadornes.rscircuits.part.PartCircuit.drawHighlight(PartCircuit.java:683)
	at mcmultipart.block.BlockMultipartContainer.onDrawBlockHighlight(BlockMultipartContainer.java:521)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_28_BlockMultipartContainer_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
```
Now to put down the modpack there is not much to show. but here is the list:

```
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2151-universal.jar) 
	UCHIJA	Forge{12.18.2.2151} [Minecraft Forge] (forge-1.10.2-12.18.2.2151-universal.jar) 
	UCHIJA	backpack{3.0.1} [Backpack] (backpack-3.0.1-1.10.2.jar) 
	UCHIJA	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UCHIJA	Chameleon{1.10-2.1.9} [Chameleon] (Chameleon-1.10-2.1.9.jar) 
	UCHIJA	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UCHIJA	JEI{3.13.3.382} [Just Enough Items] (jei_1.10.2-3.13.3.382.jar) 
	UCHIJA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.1.jar) 
	UCHIJA	IC2{2.2.999} [Industrial Craft Classic] (IC2Classic Version 1.3.3.4.jar) 
	UCHIJA	forestry{5.2.16.327} [Forestry] (forestry_1.10.2-5.2.16.327.jar) 
	UCHIJA	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8(1).jar) 
	UCHIJA	IC2-Classic-Spmod{0.0.0.0} [IC2 Classic Detection Helper] (IC2Classic Version 1.3.3.4.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJA	levelup{${version}} [Level Up!] (LevelUp!-0.12.4-1.10.2.jar) 
	UCHIJA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJA	randomthings{3.7.7} [Random Things] (RandomThings-MC1.10.2-3.7.7.jar) 
	UCHIJA	reap{1.3.3} [Reap Mod] (ReapMod 1.3.3.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.4.6} [Storage Drawers] (StorageDrawers-1.10.2-3.4.6.jar) 
	UCHIJA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHIJA	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.10-1.3.3.jar) 
	UCHIJA	waterstrainer{1.3.2} [Water Strainer] (WaterStrainer-1.9.4-1.3.2.jar) 
	UCHIJA	waypoints{1.10.2-1.2.2} [waypoints] (waypoints-1.10.2-1.2.2.jar) 
```
Is there a way to fix it fast or do you need more information?

**Comment by Speiger** [comment]
after continue testing. Basicly all redstone-wire related stuff causes crashes...
I can not even use the mod because it keeps crashing clients...

Would be nice if you fix that.

**Comment by cookta2012** [comment]
How old is your computer and are you using Optifine because this is a common issue with Optifine

**Comment by cookta2012** [comment]
Duplicate: https://github.com/amadornes/SCM-Localization-Issues/issues/145

**Comment by Speiger** [comment]
ok there is an issue. My computer requires Optifine else i wont be able to even really play....
So there is no real option to remove it... @cookta2012
