### ISSUE TITLE
"Error while updating circuit" during server startup

### ISSUE THREAD

**Issue by Ricket** [amadornes/SCM-Localization-Issues#301]
My base is chunkloaded, I have only one area with super circuit maker circuits. Got the following stack trace on startup.

SuperCircuitMaker-1.0.4.jar from Direwolf20-1.10 modpack version 1.2.1.

```
[16:51:49] [Server thread/ERROR] [rscircuits]: Error while updating circuit.
java.lang.NullPointerException
        at com.amadornes.rscircuits.component.digital.ComponentLever.onScheduledTick(ComponentLever.java:155) ~[ComponentLever.class:?]
        at com.amadornes.rscircuits.circuit.Circuit.lambda$null$22(Circuit.java:829) ~[Circuit.class:?]
        at java.util.HashMap.forEach(HashMap.java:1288) ~[?:1.8.0_111]
        at com.amadornes.rscircuits.circuit.Circuit.lambda$tickScheduled$23(Circuit.java:828) ~[Circuit.class:?]
        at java.util.HashMap.forEach(HashMap.java:1288) ~[?:1.8.0_111]
        at com.amadornes.rscircuits.circuit.Circuit.tickScheduled(Circuit.java:827) ~[Circuit.class:?]
        at com.amadornes.rscircuits.part.PartCircuit.func_73660_a(PartCircuit.java:530) [PartCircuit.class:?]
        at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:328) [TileMultipartContainer$Ticking.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1804) [aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) [ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```

**Comment by Ricket** [comment]
Uh.. looks like some of my circuit is ruined due to this error. :(

![image](https://cloud.githubusercontent.com/assets/196978/21533092/2ab09c1c-cd25-11e6-99f3-37df9081730a.png)

edit: breaking & replacing did fix this though

**Comment by Ricket** [comment]
My circuit had a lot of issues. Signals not being received or being stuck. I had to break and replace things to try and get it working again. Finally I shut down the server and started it back up, and now it is all working as expected. I guess this exception had more consequences than it seemed.
