### ISSUE TITLE
Linux | Minecraft Crash when I show on a placed Circuitplate with a Piece of Redstone !!!

### ISSUE THREAD

**Issue by DanHCraft** [amadornes/SCM-Localization-Issues#311]
If I place a Circuit and I show on the Circuit with a Piece of Redstone in my Hand, Minecraft crash with the following Crash Report:

---- Minecraft Crash Report ------------------------------------------------------------------------------------------------------

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.2.108-universal.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 14.01.17 15:39
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.renderer.RenderGlobal.func_189694_a(RenderGlobal.java:2746)
	at net.minecraft.client.renderer.RenderGlobal.func_189697_a(RenderGlobal.java:2739)
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:2724)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1748)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.renderer.RenderGlobal.func_189694_a(RenderGlobal.java:2746)
	at net.minecraft.client.renderer.RenderGlobal.func_189697_a(RenderGlobal.java:2739)
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:2724)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1748)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DanHCraft'/439, l='MpServer', x=-6,60, y=64,00, z=-214,88]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,-180), Chunk: (at 8,4,12 in 0,-12; contains blocks 0,0,-192 to 15,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1143 game time, 1143 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 88 total; [EntityPig['Pig'/0, l='MpServer', x=-6,30, y=64,00, z=-189,75], EntityPig['Pig'/1, l='MpServer', x=-6,41, y=64,00, z=-202,30], EntityPig['Pig'/2, l='MpServer', x=0,66, y=64,00, z=-196,09], EntityBat['Bat'/1538, l='MpServer', x=-47,61, y=21,75, z=-191,38], EntityPig['Pig'/3, l='MpServer', x=6,25, y=64,00, z=-185,43], EntitySheep['Sheep'/4, l='MpServer', x=5,45, y=61,93, z=-175,50], EntityBat['Bat'/1540, l='MpServer', x=-16,82, y=22,08, z=-193,69], EntitySheep['Sheep'/5, l='MpServer', x=5,45, y=62,15, z=-174,51], EntitySheep['Sheep'/6, l='MpServer', x=5,78, y=64,00, z=-179,49], EntitySheep['Sheep'/7, l='MpServer', x=1,50, y=64,00, z=-176,50], EntityCreeper['Creeper'/1543, l='MpServer', x=-4,50, y=18,00, z=-176,50], EntitySkeleton['Skeleton'/1544, l='MpServer', x=-1,50, y=18,00, z=-176,50], EntitySkeleton['Skeleton'/1545, l='MpServer', x=-1,50, y=18,00, z=-176,50], EntityZombie['Zombie'/1559, l='MpServer', x=-16,50, y=24,00, z=-261,50], EntityBat['Bat'/1564, l='MpServer', x=11,25, y=24,87, z=-208,59], EntityBat['Bat'/1566, l='MpServer', x=17,70, y=26,17, z=-206,18], EntityBat['Bat'/1567, l='MpServer', x=12,77, y=25,77, z=-206,28], EntityBat['Bat'/1568, l='MpServer', x=11,71, y=24,76, z=-209,43], EntityPlayerSP['DanHCraft'/439, l='MpServer', x=-6,60, y=64,00, z=-214,88], EntitySquid['Squid'/761, l='MpServer', x=24,47, y=46,00, z=-204,57], EntitySquid['Squid'/770, l='MpServer', x=-9,76, y=51,88, z=-244,25], EntityBat['Bat'/1282, l='MpServer', x=-10,38, y=24,25, z=-187,00], EntitySquid['Squid'/771, l='MpServer', x=-7,88, y=50,46, z=-250,93], EntitySquid['Squid'/772, l='MpServer', x=-26,54, y=55,48, z=-244,47], EntitySquid['Squid'/785, l='MpServer', x=12,33, y=55,20, z=-206,22], EntitySquid['Squid'/786, l='MpServer', x=-7,56, y=54,06, z=-234,85], EntitySquid['Squid'/787, l='MpServer', x=21,79, y=51,40, z=-224,69], EntitySquid['Squid'/788, l='MpServer', x=16,82, y=60,16, z=-218,04], EntityBat['Bat'/1307, l='MpServer', x=-3,50, y=21,10, z=-230,25], EntityBat['Bat'/1310, l='MpServer', x=-32,25, y=15,31, z=-194,22], EntityZombie['Zombie'/1320, l='MpServer', x=4,50, y=20,00, z=-231,50], EntitySpider['Spider'/1324, l='MpServer', x=0,50, y=18,00, z=-213,50], EntitySquid['Squid'/819, l='MpServer', x=23,12, y=50,55, z=-223,94], EntitySquid['Squid'/820, l='MpServer', x=20,62, y=59,39, z=-226,96], EntitySquid['Squid'/821, l='MpServer', x=-8,63, y=49,57, z=-232,85], EntitySquid['Squid'/831, l='MpServer', x=-42,86, y=55,57, z=-188,00], EntityZombie['Zombie'/1347, l='MpServer', x=-53,50, y=25,00, z=-191,50], EntityCreeper['Creeper'/1351, l='MpServer', x=5,77, y=21,00, z=-228,49], EntitySquid['Squid'/841, l='MpServer', x=-39,91, y=57,62, z=-186,61], EntitySquid['Squid'/847, l='MpServer', x=-41,71, y=56,36, z=-189,04], EntitySquid['Squid'/848, l='MpServer', x=-40,76, y=55,04, z=-193,20], EntitySquid['Squid'/849, l='MpServer', x=33,21, y=51,25, z=-206,69], EntityZombie['Zombie'/1365, l='MpServer', x=-44,50, y=20,00, z=-196,50], EntityCreeper['Creeper'/1366, l='MpServer', x=30,50, y=23,00, z=-206,50], EntityCreeper['Creeper'/1368, l='MpServer', x=29,50, y=23,00, z=-209,50], EntityCreeper['Creeper'/1369, l='MpServer', x=32,60, y=23,00, z=-209,15], EntityZombie['Zombie'/1377, l='MpServer', x=-0,50, y=18,00, z=-210,50], EntitySquid['Squid'/865, l='MpServer', x=-47,44, y=55,88, z=-223,94], EntitySquid['Squid'/866, l='MpServer', x=-51,86, y=56,79, z=-219,10], EntitySkeleton['Skeleton'/1379, l='MpServer', x=-1,50, y=18,00, z=-212,50], EntitySquid['Squid'/869, l='MpServer', x=-36,27, y=48,02, z=-185,39], EntitySquid['Squid'/871, l='MpServer', x=3,31, y=55,70, z=-246,01], EntitySquid['Squid'/872, l='MpServer', x=-21,80, y=52,65, z=-245,81], EntitySquid['Squid'/873, l='MpServer', x=-10,42, y=58,44, z=-244,40], EntitySquid['Squid'/874, l='MpServer', x=-8,93, y=58,37, z=-229,89], EntitySquid['Squid'/876, l='MpServer', x=-18,97, y=57,98, z=-174,47], EntitySquid['Squid'/893, l='MpServer', x=-14,92, y=53,96, z=-224,08], EntityCreeper['Creeper'/1410, l='MpServer', x=17,15, y=24,00, z=-220,17], EntitySquid['Squid'/903, l='MpServer', x=-19,87, y=42,87, z=-222,19], EntitySquid['Squid'/908, l='MpServer', x=-21,64, y=49,29, z=-215,93], EntitySquid['Squid'/909, l='MpServer', x=-29,17, y=52,15, z=-218,91], EntityZombie['Zombie'/1421, l='MpServer', x=-31,50, y=27,00, z=-242,50], EntitySquid['Squid'/910, l='MpServer', x=-17,24, y=55,75, z=-250,33], EntityZombie['Zombie'/1422, l='MpServer', x=-33,70, y=27,00, z=-241,50], EntitySquid['Squid'/911, l='MpServer', x=4,66, y=55,17, z=-248,38], EntitySquid['Squid'/912, l='MpServer', x=-35,24, y=61,29, z=-197,29], EntityCreeper['Creeper'/1425, l='MpServer', x=-28,50, y=28,00, z=-244,50], EntitySquid['Squid'/914, l='MpServer', x=-34,20, y=56,76, z=-230,21], EntityCreeper['Creeper'/1426, l='MpServer', x=-28,50, y=28,00, z=-241,50], EntitySquid['Squid'/915, l='MpServer', x=31,83, y=61,73, z=-244,70], EntityCreeper['Creeper'/1427, l='MpServer', x=-32,96, y=27,00, z=-241,50], EntityCreeper['Creeper'/1428, l='MpServer', x=-29,50, y=28,00, z=-244,50], EntitySquid['Squid'/918, l='MpServer', x=18,11, y=61,44, z=-246,52], EntityCreeper['Creeper'/1449, l='MpServer', x=24,50, y=23,00, z=-205,50], EntityCreeper['Creeper'/1450, l='MpServer', x=25,50, y=23,00, z=-206,50], EntityZombie['Zombie'/1452, l='MpServer', x=27,50, y=23,00, z=-205,50], EntityEnderman['Enderman'/1458, l='MpServer', x=23,41, y=24,00, z=-208,51], EntityZombie['Zombie'/1471, l='MpServer', x=-39,55, y=26,00, z=-185,28], EntityZombie['Zombie'/1476, l='MpServer', x=-54,29, y=18,00, z=-167,50], EntityBat['Bat'/1491, l='MpServer', x=-1,50, y=18,57, z=-213,60], EntityBat['Bat'/1492, l='MpServer', x=-2,40, y=15,01, z=-202,37], EntitySkeleton['Skeleton'/1495, l='MpServer', x=-8,50, y=23,00, z=-186,50], EntitySkeleton['Skeleton'/1501, l='MpServer', x=-31,50, y=15,00, z=-188,50], EntityCreeper['Creeper'/1512, l='MpServer', x=-41,50, y=26,00, z=-183,50], EntityCreeper['Creeper'/1517, l='MpServer', x=13,50, y=24,00, z=-224,50], EntityCreeper['Creeper'/1523, l='MpServer', x=12,50, y=25,00, z=-205,50], EntityCreeper['Creeper'/1524, l='MpServer', x=14,50, y=25,00, z=-206,50], EntityCreeper['Creeper'/1525, l='MpServer', x=14,50, y=25,00, z=-205,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.4.0-59-generic
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 89647096 bytes (85 MB) / 628523008 bytes (599 MB) up to 4260102144 bytes (4062 MB)
	JVM Flags: 23 total; -Xmx4G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=75 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10 -XX:ParallelGCThreads=4
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D1 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	CodeChickenLib{2.4.2.108} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.2.108-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.3.4.90} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.4.90-universal.jar) 
	UCHIJAAAA	JEI{3.12.8.323} [Just Enough Items] (jei_1.10.2-3.12.8.323.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.2.108-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 11.2.0' Renderer: 'Mesa DRI Intel(R) Sandybridge Mobile '
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Mesa DRI Intel(R) Sandybridge Mobile  GL version 3.0 Mesa 11.2.0, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Skyrim_resourcepack_v4.1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-2312M CPU @ 2.10GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D1
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0 Mesa 11.2.0
	OpenGlRenderer: Mesa DRI Intel(R) Sandybridge Mobile 
	OpenGlVendor: Intel Open Source Technology Center
	CpuCount: 4

**Comment by kane-thornwyrd** [comment]
I'll try to investigate tonight, please, next time use gist :)

**Comment by kane-thornwyrd** [comment]
Can you try without Optifine and also provide a modlist ?

**Comment by DanHCraft** [comment]
Without Optifine I can use the Mod, without Errors.

Modlist:
Minecraft Coder Pack 9.19
Forge Mod Loader 8.0.99.99
Minecraft Forge 12.18.3.2185
CodeChicken Lib 2.4.2.108
CodeChicken Core 2.3.4.90
Just Enough Items 3.12.8.323
MCMultiPart 1.3.0
Super Circuit Maker 1.0.4
