### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [amadornes/SCM-Localization-Issues#314]
I really dont know how to read a crash report but when i has pick 64 piles of glowing redstone my minecraft has crashed when now when i try start my minecraft world that crash again without i do anything please help me i love soo much that mod and thank you for do it !!! care you help me ??
PS: i leave the crash below

---- Minecraft Crash Report ----
WARNING: coremods are present:
BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
AppEngCore (appliedenergistics2-rv4-alpha-8.jar)
CCCDeobfPlugin (unknown)
DLFMLCorePlugin (DynamicLights-1.10.2.jar)
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-15.jar)
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.2.51-universal.jar)
CodeChickenCorePlugin (CodeChickenCore-1.10.2-Latest.jar)
LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)
Contact their authors BEFORE contacting forge
// Why is it breaking :(
Time: 1/22/17 5:17 PM
Description: Tesselating block model
java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=ticking, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in ExtendedBlockState{block=mcmultipart:multipart, properties=[ticking]}
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
at mcmultipart.block.BlockMultipartContainer.func_176201_c(BlockMultipartContainer.java:484)
at net.minecraft.block.state.BlockStateBase.getMetadata(BlockStateBase.java:63)
at RenderEnv.getMetadata(RenderEnv.java:133)
at CustomColors.getColorMultiplier(CustomColors.java:888)
at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:220)
at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:119)
at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)
at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
at com.amadornes.rscircuits.component.SimpleFactory.draw(SimpleFactory.java:166)
at com.amadornes.rscircuits.component.wire.ComponentWire$Factory.drawPlacement(ComponentWire.java:617)
at com.amadornes.rscircuits.component.wire.ComponentWire$Factory.drawPlacement(ComponentWire.java:533)
at com.amadornes.rscircuits.part.PartCircuit.drawComponentHighlight(PartCircuit.java:721)
at com.amadornes.rscircuits.part.PartCircuit.drawHighlight(PartCircuit.java:683)
at mcmultipart.block.BlockMultipartContainer.onDrawBlockHighlight(BlockMultipartContainer.java:521)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_157_BlockMultipartContainer_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at Reflector.callBoolean(Reflector.java:352)
at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1748)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1336)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
at org.multimc.EntryPoint.listen(EntryPoint.java:162)
at org.multimc.EntryPoint.main(EntryPoint.java:53)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Client thread
Stacktrace:
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
at mcmultipart.block.BlockMultipartContainer.func_176201_c(BlockMultipartContainer.java:484)
at net.minecraft.block.state.BlockStateBase.getMetadata(BlockStateBase.java:63)
at RenderEnv.getMetadata(RenderEnv.java:133)
at CustomColors.getColorMultiplier(CustomColors.java:888)
at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:220)
at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:119)
at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)
-- Block model being tesselated --
Details:
Block: mcmultipart:multipart[back=none,front=none,left=none,right=none]
Block location: World: (3,75,-14), Chunk: (at 3,4,2 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Using AO: true
Stacktrace:
at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
at com.amadornes.rscircuits.component.SimpleFactory.draw(SimpleFactory.java:166)
at com.amadornes.rscircuits.component.wire.ComponentWire$Factory.drawPlacement(ComponentWire.java:617)
at com.amadornes.rscircuits.component.wire.ComponentWire$Factory.drawPlacement(ComponentWire.java:533)
at com.amadornes.rscircuits.part.PartCircuit.drawComponentHighlight(PartCircuit.java:721)
at com.amadornes.rscircuits.part.PartCircuit.drawHighlight(PartCircuit.java:683)
at mcmultipart.block.BlockMultipartContainer.onDrawBlockHighlight(BlockMultipartContainer.java:521)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_157_BlockMultipartContainer_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at Reflector.callBoolean(Reflector.java:352)
at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1748)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP['Hortaseca21'/370, l='MpServer', x=3.10, y=74.00, z=-11.59]]
Chunk stats: MultiplayerChunkCache: 156, 156
Level seed: 0
Level generator: ID 04 - customized, ver 0. Features enabled: false
Level generator options: 
Level spawn location: World: (-100,64,-124), Chunk: (at 12,4,4 in -7,-8; contains blocks -112,0,-128 to -97,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Level time: 81195 game time, 81195 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Forced entities: 31 total; [EntityBat['Bat'/450, l='MpServer', x=38.54, y=37.12, z=-75.15], EntityFlicker['entity.arsmagica2.Flicker.name'/259, l='MpServer', x=21.75, y=77.00, z=-1.25], EntityCartBasic['entity.MinecartRideable.name'/197, l='MpServer', x=-67.50, y=48.00, z=-63.24], EntitySpider['Spider'/198, l='MpServer', x=-66.07, y=43.00, z=14.08], EntityCreeper['Creeper'/199, l='MpServer', x=-75.50, y=40.00, z=0.50], EntitySkeleton['Skeleton'/201, l='MpServer', x=-73.47, y=42.00, z=20.20], EntitySkeleton['Skeleton'/268, l='MpServer', x=31.44, y=20.00, z=-89.09], EntityCreeper['Creeper'/205, l='MpServer', x=-38.50, y=45.00, z=-38.50], EntitySquid['Squid'/398, l='MpServer', x=-10.67, y=54.99, z=42.39], EntityZombie['Zombie'/206, l='MpServer', x=-36.50, y=28.00, z=64.50], EntitySquid['Squid'/399, l='MpServer', x=-12.69, y=53.55, z=46.60], EntitySquid['Squid'/400, l='MpServer', x=-10.52, y=53.14, z=45.05], EntitySquid['Squid'/401, l='MpServer', x=-12.77, y=53.48, z=43.75], EntityZombie['Zombie'/468, l='MpServer', x=13.35, y=23.00, z=-48.65], EntityBat['Bat'/535, l='MpServer', x=-66.74, y=43.69, z=14.37], EntityItem['item.item.stick'/283, l='MpServer', x=63.02, y=95.00, z=14.09], EntityCreeper['Creeper'/667, l='MpServer', x=33.50, y=44.00, z=-78.50], EntitySpider['Spider'/284, l='MpServer', x=53.50, y=80.00, z=10.50], EntityCreeper['Creeper'/668, l='MpServer', x=33.50, y=44.00, z=-83.50], EntityCreeper['Creeper'/606, l='MpServer', x=-49.50, y=31.00, z=48.50], EntityCreeper['Creeper'/671, l='MpServer', x=-62.50, y=44.00, z=12.50], EntityCreeper['Creeper'/236, l='MpServer', x=11.50, y=25.00, z=-45.50], EntityFlicker['entity.arsmagica2.Flicker.name'/556, l='MpServer', x=-30.28, y=70.59, z=-73.50], EntitySkeleton['Skeleton'/624, l='MpServer', x=-58.50, y=47.00, z=9.50], EntityPlayerSP['Hortaseca21'/370, l='MpServer', x=3.10, y=74.00, z=-11.59], EntityBat['Bat'/181, l='MpServer', x=-70.56, y=37.43, z=-5.48], EntitySkeleton['Skeleton'/629, l='MpServer', x=-73.50, y=27.00, z=49.50], EntityZombie['Zombie'/503, l='MpServer', x=-41.50, y=20.00, z=60.50], EntityBat['Bat'/184, l='MpServer', x=-76.87, y=43.86, z=2.96], EntitySkeleton['Skeleton'/573, l='MpServer', x=-40.50, y=28.00, z=62.50], EntitySkeleton['Skeleton'/574, l='MpServer', x=-39.50, y=28.00, z=62.50]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
at org.multimc.EntryPoint.listen(EntryPoint.java:162)
at org.multimc.EntryPoint.main(EntryPoint.java:53)
-- System Details --
Details:
Minecraft Version: 1.10.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_111, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1895131936 bytes (1807 MB) / 5423759360 bytes (5172 MB) up to 7639400448 bytes (7285 MB)
JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx8196m
IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
FML: MCP 9.32 Powered by Forge 12.18.2.2151 Optifine OptiFine_1.10.2_HD_U_D4 42 mods loaded, 42 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2151-universal.jar) 
UCHIJAAAA Forge{12.18.2.2151} [Minecraft Forge] (forge-1.10.2-12.18.2.2151-universal.jar) 
UCHIJAAAA appliedenergistics2-core{rv4-alpha-8} [Applied Energistics 2 Core] (minecraft.jar) 
UCHIJAAAA CodeChickenCore{2.1.7.77} [CodeChicken Core] (minecraft.jar) 
UCHIJAAAA appliedenergistics2{rv4-alpha-8} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-8.jar) 
UCHIJAAAA AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-15.jar) 
UCHIJAAAA arsmagica2{1.5.015} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-15.jar) 
UCHIJAAAA Baubles{1.3.6} [Baubles] (Baubles-1.10.2-1.3.6.jar) 
UCHIJAAAA BetterAchievements{0.3.0.28} [Better Achievements] (BetterAchievements-1.10.2-0.3.0.28.jar) 
UCHIJAAAA BetterFoliage{2.1.0} [Better Foliage] (BetterFoliage-MC1.10-2.1.0.jar) 
UCHIJAAAA Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
UCHIJAAAA chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-Mod-1.10.2.jar) 
UCHIJAAAA mcmultipart{2.0.0_88} [MCMultiPart] (MCMultiPart-experimental-2.0.0_88-universal.jar) 
UCHIJAAAA chiselsandbits{11.3} [Chisels & Bits] (chiselsandbits-11.3.jar) 
UCHIJAAAA DynamicLights{1.4.3} [Dynamic Lights] (DynamicLights-1.10.2.jar) 
UCHIJAAAA DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module] (DynamicLights-1.10.2.jar) 
UCHIJAAAA DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module] (DynamicLights-1.10.2.jar) 
UCHIJAAAA DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.10.2.jar) 
UCHIJAAAA DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.10.2.jar) 
UCHIJAAAA DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.10.2.jar) 
UCHIJAAAA DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.10.2.jar) 
UCHIJAAAA DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.10.2.jar) 
UCHIJAAAA DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.10.2.jar) 
UCHIJAAAA DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.10.2.jar) 
UCHIJAAAA EnderStorage{2.1.3.71} [EnderStorage] (Ender-Storage-Mod-1.10.2.jar) 
UCHIJAAAA endercore{1.10.2-0.4.1.56-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.56-beta.jar) 
UCHIJAAAA JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
UCHIJAAAA Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
UCHIJAAAA EnderIO{1.10.2-3.0.1.120_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.120_beta.jar) 
UCHIJAAAA HardcoreQuesting{1.10.2-5.0.0beta4} [Hardcore Questing Mode] (HQM-New Heights-1.10.2-5.0.0beta4.jar) 
UCHIJAAAA mantle{1.10.2-1.1.4.203} [Mantle] (Mantle-1.10.2-1.1.4.jar) 
UCHIJAAAA tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
UCHIJAAAA immersiveengineering{0.10-52} [Immersive Engineering] (ImmersiveEngineering-0.10-52.jar) 
UCHIJAAAA LunatriusCore{1.1.2.36} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
UCHIJAAAA InGameInfoXML{2.8.1.85} [InGame Info XML] (InGameInfoXML-1.10.2-2.8.1.85-universal.jar) 
UCHIJAAAA journeymap{1.10.2-5.3.1} [JourneyMap] (journeymap-1.10.2-5.3.1.jar) 
UCHIJAAAA Mekanism{9.2.1} [Mekanism] (Mekanism-1.10.2-9.2.1.295.jar) 
UCHIJAAAA testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
UCHIJAAAA railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
UCHIJAAAA SophisticatedWolves{3.6.1} [SophisticatedWolves] (SophisticatedWolves-3.6.4.jar) 
UCHIJAAAA rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
mods.betterfoliage.loader.BetterFoliageTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
com.enderio.core.common.transform.EnderCoreTransformer
AppEngCore (appliedenergistics2-rv4-alpha-8.jar)
appeng.coremod.asm.ASMIntegration
CCCDeobfPlugin (unknown)

DLFMLCorePlugin (DynamicLights-1.10.2.jar)
atomicstryker.dynamiclights.common.DLTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-15.jar)
am2.asm.Transformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.2.51-universal.jar)
codechicken.lib.asm.ClassHeirachyManager
codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-Latest.jar)
codechicken.core.asm.TweakTransformer
codechicken.core.asm.DelegatedTransformer
codechicken.core.asm.DefaultImplementationTransformer
LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)

GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1101.0' Renderer: 'AMD Radeon(TM) R6 Graphics'
AE2 Version: alpha rv4-alpha-8 for Forge 12.18.2.2139
Pulsar/tconstruct loaded Pulses: 
- TinkerCommons (Enabled/Forced)
- TinkerWorld (Enabled/Not Forced)
- TinkerTools (Enabled/Not Forced)
- TinkerHarvestTools (Enabled/Forced)
- TinkerMeleeWeapons (Enabled/Forced)
- TinkerRangedWeapons (Enabled/Forced)
- TinkerModifiers (Enabled/Forced)
- TinkerSmeltery (Enabled/Not Forced)
- TinkerGadgets (Enabled/Not Forced)
- TinkerOredict (Enabled/Forced)
- TinkerIntegration (Enabled/Forced)
- TinkerFluids (Enabled/Forced)
- TinkerMaterials (Enabled/Forced)
- TinkerModelRegister (Enabled/Forced)
- chiselsandbitsIntegration (Enabled/Not Forced)
- WailaIntegration (Enabled/Not Forced)
CodeChickenCore: ignoreInvalidMCVersion state: false
EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
* Optifine is installed. This is NOT supported.
* An unknown AE2 API is installed (rv4 from appliedenergistics2-rv4-alpha-8.jar).
Ender IO was build against API version rv2 and may or may not work with a newer version.
This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
Detailed RF API diagnostics:
* RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/António/Desktop/Jogos/MultiMC/instances/HAJCraft/minecraft/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/EnergyStorage.class
* RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/António/Desktop/Jogos/MultiMC/instances/HAJCraft/minecraft/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/IEnergyConnection.class
* RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/António/Desktop/Jogos/MultiMC/instances/HAJCraft/minecraft/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/IEnergyContainerItem.class
* RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/António/Desktop/Jogos/MultiMC/instances/HAJCraft/minecraft/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/IEnergyHandler.class
* RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/António/Desktop/Jogos/MultiMC/instances/HAJCraft/minecraft/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/IEnergyProvider.class
* RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/António/Desktop/Jogos/MultiMC/instances/HAJCraft/minecraft/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/IEnergyReceiver.class
* RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/António/Desktop/Jogos/MultiMC/instances/HAJCraft/minecraft/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/IEnergyStorage.class
* RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/António/Desktop/Jogos/MultiMC/instances/HAJCraft/minecraft/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/ItemEnergyContainer.class
* RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/António/Desktop/Jogos/MultiMC/instances/HAJCraft/minecraft/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/TileEnergyHandler.class
Detailed Tesla API diagnostics:
* Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
* Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
* Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
* Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
* Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
* Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
* Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
* Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
* Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
* Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
* Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)
AE2 Integration: IC2:OFF, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF
Launched Version: MultiMC5
LWJGL: 2.9.1
OpenGL: AMD Radeon(TM) R6 Graphics GL version 4.5.13399 Compatibility Profile Context 15.201.1101.0, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G
OptiFine Version: OptiFine_1.10.2_HD_U_D4
Render Distance Chunks: 6
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1101.0
OpenGlRenderer: AMD Radeon(TM) R6 Graphics
OpenGlVendor: ATI Technologies Inc.
CpuCount: 4

**Comment by TheOldOne822** [comment]
OptiFine  is not compatible with SCM

**Comment by ghost** [comment]
I found the problem one of the congigs in optifine do the crash i delete
the optfine configs.txt and that start working again thanks I like a lots
of that mod soo I try fix that for hours continue developping it and dont
worry  with the problem cause problebly any more will have it cause its a
advanced option that anyone usually uses but I doesnt remmenber the made
sorry

Em 27/01/2017 4:45 a.m., "TheOldOne822" <notifications@github.com> escreveu:
