### ISSUE TITLE
Bundled and Redstone-impregnated sticks in hand cause crash

### ISSUE THREAD

**Issue by MoshiBar** [amadornes/SCM-Localization-Issues#320]
Minecraft 1.10.2
Super Circuit Maker 1.0.4
McMultipart 1.3.0

When I have a bundled or redstone impregnated stick in my hand and look at a circuit board, Minecraft crashes

**Comment by dokranke** [comment]
Could you upload a crashlog?

**Comment by MoshiBar** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 2/5/17 2:02 PM
Description: Tesselating block model

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=ticking, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in ExtendedBlockState{block=mcmultipart:multipart, properties=[ticking]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at mcmultipart.block.BlockMultipartContainer.func_176201_c(BlockMultipartContainer.java:484)
	at net.minecraft.block.state.BlockStateBase.getMetadata(BlockStateBase.java:63)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:470)
	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:370)
	at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:299)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:113)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:89)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:60)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
	at com.amadornes.rscircuits.component.SimpleFactory.draw(SimpleFactory.java:166)
	at com.amadornes.rscircuits.component.SimpleFactory.draw(SimpleFactory.java:116)
	at com.amadornes.rscircuits.component.SimpleFactory.drawPlacement(SimpleFactory.java:86)
	at com.amadornes.rscircuits.component.SimpleFactory.drawPlacement(SimpleFactory.java:37)
	at com.amadornes.rscircuits.part.PartCircuit.drawComponentHighlight(PartCircuit.java:721)
	at com.amadornes.rscircuits.part.PartCircuit.drawHighlight(PartCircuit.java:683)
	at mcmultipart.block.BlockMultipartContainer.onDrawBlockHighlight(BlockMultipartContainer.java:521)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_BlockMultipartContainer_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161)
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callBoolean(Reflector.java:532)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1746)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1555)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1334)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at mcmultipart.block.BlockMultipartContainer.func_176201_c(BlockMultipartContainer.java:484)
	at net.minecraft.block.state.BlockStateBase.getMetadata(BlockStateBase.java:63)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:470)
	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:370)
	at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:299)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:113)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:89)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:60)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)

-- Block model being tesselated --
Details:
	Block: mcmultipart:multipart
	Block location: World: (759,56,-988), Chunk: (at 7,3,4 in 47,-62; contains blocks 752,0,-992 to 767,255,-977), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
	at com.amadornes.rscircuits.component.SimpleFactory.draw(SimpleFactory.java:166)
	at com.amadornes.rscircuits.component.SimpleFactory.draw(SimpleFactory.java:116)
	at com.amadornes.rscircuits.component.SimpleFactory.drawPlacement(SimpleFactory.java:86)
	at com.amadornes.rscircuits.component.SimpleFactory.drawPlacement(SimpleFactory.java:37)
	at com.amadornes.rscircuits.part.PartCircuit.drawComponentHighlight(PartCircuit.java:721)
	at com.amadornes.rscircuits.part.PartCircuit.drawHighlight(PartCircuit.java:683)
	at mcmultipart.block.BlockMultipartContainer.onDrawBlockHighlight(BlockMultipartContainer.java:521)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_BlockMultipartContainer_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161)
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callBoolean(Reflector.java:532)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1746)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1555)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Kronos_019'/0, l='MpServer', x=758.88, y=56.13, z=-987.29]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (769,4,-983), Chunk: (at 1,0,9 in 48,-62; contains blocks 768,0,-992 to 783,255,-977), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 54950 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Kronos_019'/0, l='MpServer', x=758.88, y=56.13, z=-987.29]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 392873312 bytes (374 MB) / 892862464 bytes (851 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2219 Optifine OptiFine_1.10.2_HD_U_D6 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2219-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2219} [Minecraft Forge] (forge-1.10.2-12.18.3.2219-universal.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJAAAA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	Loaded coremods (and transformers): 
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 6530D'
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6530D GL version 4.5.13399 Compatibility Profile Context 15.201.1151.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.11-rv1.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A6-3620 APU with Radeon(tm) HD Graphics
	OptiFine Version: OptiFine_1.10.2_HD_U_D6
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.0
	OpenGlRenderer: AMD Radeon HD 6530D
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by dokranke** [comment]
The mcmp 1.3 build os still experimental (and can be unstable) try a older one. Then it should work.

**Comment by MoshiBar** [comment]
I have tried other versions with no results
EDIT: Even the release 1.4.0 mcmp doesn't work
