### ISSUE TITLE
Tesselation crash.

### ISSUE THREAD

**Issue by dinckelman** [amadornes/SCM-Localization-Issues#341]
**Modpack Name:** DW20 1.10
**Modpack Version:** 1.9. Still present in 1.9.1
**SCM Version:** 1.0.4
**Forge Version:** 12.18.3.2254
**Repeatable?:** 100% success, the process is repeatable with any new or existing
**Link to Log:**
**Short Version:**

> The game crashed whilst tesselating block model
> Error: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=ticking, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in ExtendedBlockState{block=mcmultipart:multipart, properties=[ticking]}

**Full Log:** https://pastebin.com/t9Y4SW3s

**Issue Details:**
After updating to version 1.9 of the pack, a rendering issue occurred with all SuperCircuitMaker circuits in my world. [This is how it looks.](https://i.imgur.com/4s7tNTw.png) The circuit works just fine, but if i try to take it apart (or break and replace), the game immediately crashes and it is impossible to log back in unless a world restore is performed. Worth noting that the server itself never crashes. Any new circuit does also cause this issue right away, even if it's just a blank circuit board

**Updates/Clarifications:** This issue is not caused by a shader-pack/resource-pack. Additionally, this is confirmed to be a server-side issue.

**Comment by dokranke** [comment]
What mcmp version is installed?

**Comment by dinckelman** [comment]
1.4.0

**Comment by BuggaNoia** [comment]
getColorMultiplier(): Got same issue on just looking at a blank circuit board. The circuit board is side by side 2 redstone conduits and one above and an RFTools Scanner on a 3rd side. (Scanner is a half hight block.)

Single player. Game crashes just on world start. (Right after/in view build-up.)

All Then Mods Expert v.026 (Minecraft 1.10.2, forge-12.18.3.2221)
SuperCircuitMaker-1.0.4
other involved Mods: RFTools, Ender IO, Actual Addition
Resource Pack: Sphax (applied to Mods above and Vanilla, not to SCM)

`Description: Tesselating block model

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=ticking, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in ExtendedBlockState{block=mcmultipart:multipart, properties=[ticking]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at mcmultipart.block.BlockMultipartContainer.func_176201_c(BlockMultipartContainer.java:484)
	at net.minecraft.block.state.BlockStateBase.getMetadata(BlockStateBase.java:63)
	at RenderEnv.getMetadata(RenderEnv.java:133)
	at CustomColors.getColorMultiplier(CustomColors.java:888)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsFlat(BlockModelRenderer.java:393)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:154)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:86)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
	at com.amadornes.rscircuits.component.SimpleFactory.draw(SimpleFactory.java:166)
	at com.amadornes.rscircuits.component.wire.ComponentWire$Factory.drawPlacement(ComponentWire.java:617)
	at com.amadornes.rscircuits.component.wire.ComponentWire$Factory.drawPlacement(ComponentWire.java:533)
	at com.amadornes.rscircuits.part.PartCircuit.drawComponentHighlight(PartCircuit.java:721)
	at com.amadornes.rscircuits.part.PartCircuit.drawHighlight(PartCircuit.java:683)
	at mcmultipart.block.BlockMultipartContainer.onDrawBlockHighlight(BlockMultipartContainer.java:521)`

**Comment by BuggaNoia** [comment]
getColorMultiplier(): Got same issue on just looking at a blank circuit board. The circuit board is side by side 2 redstone conduits and one above and an RFTools Scanner on a 3rd side. (Scanner is a half hight block.)

Single player. Game crashes just on world start. (Right after/in view build-up.)

All Then Mods Expert v.026 (Minecraft 1.10.2, forge-12.18.3.2221)
SuperCircuitMaker-1.0.4


`Description: Tesselating block model

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=ticking, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in ExtendedBlockState{block=mcmultipart:multipart, properties=[ticking]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at mcmultipart.block.BlockMultipartContainer.func_176201_c(BlockMultipartContainer.java:484)
	at net.minecraft.block.state.BlockStateBase.getMetadata(BlockStateBase.java:63)
	at RenderEnv.getMetadata(RenderEnv.java:133)
	at CustomColors.getColorMultiplier(CustomColors.java:888)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsFlat(BlockModelRenderer.java:393)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:154)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:86)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
	at com.amadornes.rscircuits.component.SimpleFactory.draw(SimpleFactory.java:166)
	at com.amadornes.rscircuits.component.wire.ComponentWire$Factory.drawPlacement(ComponentWire.java:617)
	at com.amadornes.rscircuits.component.wire.ComponentWire$Factory.drawPlacement(ComponentWire.java:533)
	at com.amadornes.rscircuits.part.PartCircuit.drawComponentHighlight(PartCircuit.java:721)
	at com.amadornes.rscircuits.part.PartCircuit.drawHighlight(PartCircuit.java:683)
	at mcmultipart.block.BlockMultipartContainer.onDrawBlockHighlight(BlockMultipartContainer.java:521)
`

**Comment by dokranke** [comment]
It's a mcmp problem not scm.
